apps/crud/models.py
from datetime import datetime
from apps.app import db
from werkzeug.security import generate_password_hash



class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    create_at = db.Column(db.DateTime, default=datetime.now)
    update_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    @property
    def password(self):
        raise AttributeError("읽어 드일 수 없음")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length
#wtforms.validators :유효성 검증 관련 모듈
#DataRequired:이 필드는 반드시 값을 써야 하는 필드
#Email:이메일 형식을 반드시 지켜야 하는 필드
#Length:입력한 값의 길이 관련


class UserForm(FlaskForm):
    username=StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다. "),
            Length(max=30, message="30문자 이내로 입력해 주세요."),
        ],
    )
    email = StringField(
        "메일 주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해 주세요."),
        ],
    )
    password =  PasswordField(
        "비밀번호",
        validators=[DataRequired(message="비밀번호는 필수입니다. ")]
    )
    submit = SubmitField("신규 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template,redirect,url_for
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@crud.route("/")
def index():
    return render_template("crud/index.html")

# @crud.route("/sql")
# def sql():

    
    # user = User(
    #     username = "사용자명4",
    #     email="flaskbook4@example.com",
    #     password_hash="비밀번호4"

    # )
    # db.session.add(user)
    # db.session.commit()


    # user=db.session.query(User).filter_by(id=1).first()
    # user.username = "사용자명2"
    # user.email="whale8941@naver.com"
    # user.password_hash="비밀번호2"
    # db.session.add(user)
    # db.session.commit()

    # user=db.session.query(User).filter_by(id=1).delete()
    # db.session.commit()

    # db.session.query(User).filter(User.username=="사용자명3").all()
    #return "콘솔 로그를 확인해 주세요" 

@crud.route("/users/new", methods=["GET","POST"])
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route("/users")
def users():
    users = User.query.all()
    return render_template("crud/index.html",users=users)

@crud.route("/users/<user_id>",methods=["GET","POST"])
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/edit.html",user=user, form=form)

@crud.route("/users/<user_id>/delete", methods=["POST"])
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('crud.static',filename='style.css')}}"/>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>사용자 신규 작성</title>
</head>
<body>
    <h2>사용자 신규 작성</h2>
    <form
        action="{{url_for('crud.create_user')}}"
        method="POST"
        novalidate="novalidate"
        >
        {{form.csrf_token}}
        <p>
            {{form.username.label}} {{form.username(placeholder="사용자명")}}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{form.email.label}} {{form.email(placeholder="메일 주소")}}
        </p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{form.password.label}} {{form.password(placeholder="비밀번호")}}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>{{ form.submit() }}</p>
    </form>
</body>
</html>

apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>사용자 편집</title>
    <link rel="stylesheet" href="{{url_for('crud.static', filename='style.css')}}"/>
</head>
<body>
    <h2>사용자 편집</h2>
    <form
        action="{{url_for('crud.edit_user',user_id=user.id)}}"
        method="POST"
        novalidate="novalidate"
        >
        {{form.csrf_token}}
        <p>
            {{form.username.label}} {{form.username(placeholder="사용자명",value=user.username)}}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{form.email.label}} {{form.email(placeholder="메일 주소",value=user.email)}}
        </p>
        {% for error in form.email.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{form.password.label}} {{form.password(placeholder="비밀번호")}}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p><input type="submit" value="갱신" /></p>
    </form>
    <form action="{{url_for('crud.delete_user', user_id=user.id)}}" method="POST">
        {{form.csrf_token}}
        <input type="submit" value="삭제">
    </form>
</body>
</html>

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title%}사용자의 알람{% endblock %}
{% block content %}
    <h2>사용자의 알람</h2>
    <a href="{{url_for('crud.create_user')}}">사용자 신규 작성</a>

    <table>
        <tr>
            <th>사용자 ID</th>
            <th>사용자명</th>
            <th>메일 주소</th>
        </tr>
        {% for user in users%}
        <tr>
            <td>
                <a href="{{url_for('crud.edit_user',user_id=user.id)}}">{{ user.id }}</a>
            </td>
            <td>{{ user.username}}</td>
            <td>{{ user.email}}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}